FROM mysql:8.0.20

ENV LANG=C.UTF-8
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes
ENV MYSQL_DATABASE=dictionary
ENV MYSQL_INITDB_SKIP_TZINFO=yes

COPY ./database/database.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"]